/* Datos Liga MX · ficha de clubes (v1 · plantilla de referencia) */
window.QA = window.QA || {};
QA.equiposData = (function () {
  function y(n) {
    return new Date().getFullYear() - n;
  }

  var clubs = [
    {
      id: "america",
      espnId: 227,
      name: "Club América",
      short: "América",
      founded: 1916,
      city: "Ciudad de México",
      stadium: "Estadio Azteca",
      capacity: 87523,
      nicknames: ["Las Águilas", "El Más Grande"],
      titles: 15,
      runnersUp: 10,
      lastTitle: "Apertura 2024",
      colors: "Amarillo y azul",
      history:
        "Fundado en 1916, el Club América es el equipo más laureado del fútbol mexicano. Su rivalidad con Chivas define el Clásico Nacional. Juega de local en el Estadio Azteca y es conocido por su afición a nivel nacional e internacional.",
      legends: [
        { name: "Cuauhtémoc Blanco", note: "Ídolo y referente ofensivo" },
        { name: "Luis Roberto Alves Zague", note: "Goleador histórico" },
        { name: "Carlos Reinoso", note: "Volante chileno emblemático" },
        { name: "Christian Benítez", note: "Chucho · goleador recordado" },
        { name: "Alfredo Tena", note: "Capitán y defensa histórico" },
      ],
      squad: [
        { n: 1, name: "Luis Malagón", pos: "POR", nat: "México" },
        { n: 3, name: "Israel Reyes", pos: "DEF", nat: "México" },
        { n: 4, name: "Sebastián Cáceres", pos: "DEF", nat: "Uruguay" },
        { n: 18, name: "Cristian Calderón", pos: "DEF", nat: "México" },
        { n: 6, name: "Jonathan dos Santos", pos: "MED", nat: "México" },
        { n: 8, name: "Álvaro Fidalgo", pos: "MED", nat: "España" },
        { n: 10, name: "Diego Valdés", pos: "MED", nat: "Chile" },
        { n: 7, name: "Brian Rodríguez", pos: "DEL", nat: "Uruguay" },
        { n: 21, name: "Henry Martín", pos: "DEL", nat: "México" },
        { n: 11, name: "Víctor Dávila", pos: "DEL", nat: "Chile" },
        { n: 9, name: "Javairô Dilrosun", pos: "DEL", nat: "Países Bajos" },
      ],
    },
    {
      id: "chivas",
      espnId: 219,
      name: "Club Deportivo Guadalajara",
      short: "Guadalajara",
      founded: 1906,
      city: "Guadalajara, Jalisco",
      stadium: "Estadio Akron",
      capacity: 46232,
      nicknames: ["Chivas", "El Rebaño Sagrado"],
      titles: 12,
      runnersUp: 10,
      lastTitle: "Clausura 2017",
      colors: "Rojo y blanco",
      history:
        "Chivas es el único grande que históricamente ha priorizado jugadores mexicanos. Fundado en 1906, es el club con más afición repartida en el país y protagonista del Clásico Nacional ante América.",
      legends: [
        { name: "Omar Bravo", note: "Máximo goleador histórico" },
        { name: "Javier Hernández", note: "Chicharito · canterano mundial" },
        { name: "Ramón Morales", note: "Volante zurdo ídolo" },
        { name: "Claudio Suárez", note: "Defensa mundialista" },
        { name: "Francisco Jara", note: "Leyenda de los 60" },
      ],
      squad: [
        { n: 1, name: "Raúl Rangel", pos: "POR", nat: "México" },
        { n: 2, name: "Alan Mozo", pos: "DEF", nat: "México" },
        { n: 3, name: "Gilberto Sepúlveda", pos: "DEF", nat: "México" },
        { n: 21, name: "José Castillo", pos: "DEF", nat: "México" },
        { n: 28, name: "Fernando Beltrán", pos: "MED", nat: "México" },
        { n: 15, name: "Érick Gutiérrez", pos: "MED", nat: "México" },
        { n: 5, name: "Víctor Guzmán", pos: "MED", nat: "México" },
        { n: 11, name: "Isaác Brizuela", pos: "DEL", nat: "México" },
        { n: 25, name: "Roberto Alvarado", pos: "DEL", nat: "México" },
        { n: 14, name: "Alan Pulido", pos: "DEL", nat: "México" },
        { n: 9, name: "José Juan Macías", pos: "DEL", nat: "México" },
      ],
    },
    {
      id: "cruz-azul",
      espnId: 218,
      name: "Cruz Azul Fútbol Club",
      short: "Cruz Azul",
      founded: 1927,
      city: "Ciudad de México",
      stadium: "Estadio Ciudad de los Deportes",
      capacity: 33000,
      nicknames: ["La Máquina", "Cementeros"],
      titles: 9,
      runnersUp: 12,
      lastTitle: "Guardianes 2021",
      colors: "Azul y blanco",
      history:
        "Nacido como equipo de la cooperativa cementera, Cruz Azul vivió su época dorada en los 70. La final de 2021 rompió una larga sequía de títulos de liga y consolidó a La Máquina como uno de los grandes.",
      legends: [
        { name: "Elías Figueroa", note: "Defensa chileno histórico" },
        { name: "Carlos Hermosillo", note: "Goleador ícono" },
        { name: "Óscar Pérez", note: "El Conejo · portero leyenda" },
        { name: "Benjamín Galindo", note: "El Maestro" },
        { name: "Francisco Palencia", note: "Delantero de antaño" },
      ],
      squad: [
        { n: 1, name: "Kevin Mier", pos: "POR", nat: "Colombia" },
        { n: 4, name: "Willier Ditta", pos: "DEF", nat: "Colombia" },
        { n: 19, name: "Carlos Rotondi", pos: "DEF", nat: "Argentina" },
        { n: 33, name: "Gonzalo Piovi", pos: "DEF", nat: "Argentina" },
        { n: 6, name: "Érik Lira", pos: "MED", nat: "México" },
        { n: 8, name: "Ignacio Rivero", pos: "MED", nat: "Uruguay" },
        { n: 18, name: "Lorenzo Faravelli", pos: "MED", nat: "Argentina" },
        { n: 9, name: "Angel Sepúlveda", pos: "DEL", nat: "México" },
        { n: 7, name: "Uriel Antuna", pos: "DEL", nat: "México" },
        { n: 11, name: "Georgios Giakoumakis", pos: "DEL", nat: "Grecia" },
        { n: 17, name: "Alejandro Marioni", pos: "DEL", nat: "Argentina" },
      ],
    },
    {
      id: "toluca",
      espnId: 223,
      name: "Deportivo Toluca Fútbol Club",
      short: "Toluca",
      founded: 1917,
      city: "Toluca, Estado de México",
      stadium: "Estadio Nemesio Díez",
      capacity: 30000,
      nicknames: ["Diablos Rojos", "El Xolo"],
      titles: 10,
      runnersUp: 8,
      lastTitle: "Clausura 2010",
      colors: "Rojo y blanco",
      history:
        "Los Diablos Rojos son uno de los clubes más estables y ganadores de México. El Nemesio Díez (La Bombonera) es famoso por su ambiente y la altura de Toluca.",
      legends: [
        { name: "José Saturnino Cardozo", note: "Máximo goleador" },
        { name: "Vicente Sánchez", note: "Volante uruguayo ídolo" },
        { name: "Hernán Cristante", note: "Portero y DT" },
        { name: "Sinha", note: "Creativo brasileño" },
        { name: "Paulo da Silva", note: "Defensa paraguayo" },
      ],
      squad: [
        { n: 1, name: "Tiago Volpi", pos: "POR", nat: "Brasil" },
        { n: 13, name: "Luan García", pos: "DEF", nat: "Brasil" },
        { n: 4, name: "Valentín Méndez", pos: "DEF", nat: "Argentina" },
        { n: 17, name: "Brian García", pos: "DEF", nat: "México" },
        { n: 14, name: "Marcel Ruiz", pos: "MED", nat: "México" },
        { n: 10, name: "Jesús Angulo", pos: "MED", nat: "México" },
        { n: 8, name: "Tomás Belmonte", pos: "MED", nat: "Argentina" },
        { n: 7, name: "Maximiliano Araújo", pos: "DEL", nat: "Uruguay" },
        { n: 25, name: "Alexis Vega", pos: "DEL", nat: "México" },
        { n: 9, name: "Paulinho", pos: "DEL", nat: "Brasil" },
        { n: 11, name: "Juan Camilo Hernández", pos: "DEL", nat: "Colombia" },
      ],
    },
    {
      id: "tigres",
      espnId: 232,
      name: "Club Tigres de la UANL",
      short: "Tigres",
      founded: 1960,
      city: "San Nicolás de los Garza, N.L.",
      stadium: "Estadio Universitario",
      capacity: 41986,
      nicknames: ["Los Felinos", "Auriazules"],
      titles: 8,
      runnersUp: 6,
      lastTitle: "Clausura 2023",
      colors: "Amarillo y azul",
      history:
        "Tigres pasó de ser un club modesto a potencia del fútbol mexicano en la era CEMEX. El Volcán es sinónimo de noches europeas y clásicos regios ante Monterrey.",
      legends: [
        { name: "Tomás Boy", note: "Ídolo histórico" },
        { name: "Walter Gaitán", note: "El Maestro" },
        { name: "André-Pierre Gignac", note: "Máximo ídolo moderno" },
        { name: "Nahuel Guzmán", note: "Portero referente" },
        { name: "Javier Aquino", note: "Extremo canterano-estrella" },
      ],
      squad: [
        { n: 1, name: "Nahuel Guzmán", pos: "POR", nat: "Argentina" },
        { n: 19, name: "Javier Aquino", pos: "DEF", nat: "México" },
        { n: 13, name: "Diego Reyes", pos: "DEF", nat: "México" },
        { n: 20, name: "Javier Aquino", pos: "MED", nat: "México" },
        { n: 5, name: "Rafael Carioca", pos: "MED", nat: "Brasil" },
        { n: 8, name: "Fernando Gorriarán", pos: "MED", nat: "Uruguay" },
        { n: 16, name: "Diego Lainez", pos: "MED", nat: "México" },
        { n: 11, name: "Juan Brunetta", pos: "MED", nat: "Argentina" },
        { n: 10, name: "André-Pierre Gignac", pos: "DEL", nat: "Francia" },
        { n: 9, name: "Nicolás Ibáñez", pos: "DEL", nat: "Argentina" },
        { n: 7, name: "Sebastián Córdova", pos: "DEL", nat: "México" },
      ],
    },
    {
      id: "monterrey",
      espnId: 220,
      name: "Club de Fútbol Monterrey",
      short: "Monterrey",
      founded: 1945,
      city: "Monterrey, Nuevo León",
      stadium: "Estadio BBVA",
      capacity: 53500,
      nicknames: ["Rayados", "La Pandilla"],
      titles: 5,
      runnersUp: 7,
      lastTitle: "Apertura 2019",
      colors: "Azul y blanco rayado",
      history:
        "Rayados es el gran rival de Tigres en el Clásico Regio. Con el Estadio BBVA como casa, ha sido protagonista en Liga MX y Concachampions.",
      legends: [
        { name: "Guillermo Franco", note: "Goleador argentino-mexicano" },
        { name: "Luis Ernesto Pérez", note: "Capitán histórico" },
        { name: "Humberto Suazo", note: "El Chupete" },
        { name: "Ricardo Osorio", note: "Defensa mundialista" },
        { name: "Jesús Arellano", note: "El Cabrito" },
      ],
      squad: [
        { n: 22, name: "Esteban Andrada", pos: "POR", nat: "Argentina" },
        { n: 3, name: "Gerardo Arteaga", pos: "DEF", nat: "México" },
        { n: 15, name: "Héctor Moreno", pos: "DEF", nat: "México" },
        { n: 33, name: "Stefan Medina", pos: "DEF", nat: "Colombia" },
        { n: 30, name: "Jorge Rodríguez", pos: "MED", nat: "Argentina" },
        { n: 8, name: "Óliver Torres", pos: "MED", nat: "España" },
        { n: 10, name: "Sergio Canales", pos: "MED", nat: "España" },
        { n: 17, name: "Jesús Corona", pos: "DEL", nat: "México" },
        { n: 9, name: "Brandon Vázquez", pos: "DEL", nat: "EE.UU." },
        { n: 7, name: "Maximiliano Meza", pos: "DEL", nat: "Argentina" },
        { n: 11, name: "Germán Berterame", pos: "DEL", nat: "Argentina" },
      ],
    },
    {
      id: "leon",
      espnId: 228,
      name: "Club León",
      short: "León",
      founded: 1944,
      city: "León, Guanajuato",
      stadium: "Estadio León (Nou Camp)",
      capacity: 31297,
      nicknames: ["La Fiera", "Esmeraldas"],
      titles: 8,
      runnersUp: 7,
      lastTitle: "Guardianes 2020",
      colors: "Verde y blanco",
      history:
        "La Fiera es uno de los clubes clásicos del Bajío. Bicampeón en la era moderna y campeón de Concacaf, mantiene una afición muy fiel en el Nou Camp.",
      legends: [
        { name: "Ángel Comizzo", note: "Portero ídolo" },
        { name: "Mauro Boselli", note: "Goleador argentino" },
        { name: "Luis Montes", note: "El Chapo" },
        { name: "Elias Hernández", note: "Extremo creativo" },
        { name: "José Francisco Fonseca", note: "Canterano y goleador" },
      ],
      squad: [
        { n: 1, name: "Rodolfo Cota", pos: "POR", nat: "México" },
        { n: 21, name: "Stiven Barreiro", pos: "DEF", nat: "Colombia" },
        { n: 25, name: "Paul Bellón", pos: "DEF", nat: "México" },
        { n: 7, name: "Iván Moreno", pos: "DEF", nat: "México" },
        { n: 8, name: "José Rodríguez", pos: "MED", nat: "España" },
        { n: 15, name: "Ángel Mena", pos: "MED", nat: "Ecuador" },
        { n: 26, name: "Fidel Ambríz", pos: "MED", nat: "México" },
        { n: 10, name: "James Rodríguez", pos: "MED", nat: "Colombia" },
        { n: 16, name: "Johan Rojas", pos: "DEL", nat: "Colombia" },
        { n: 9, name: "Federico Viñas", pos: "DEL", nat: "Uruguay" },
        { n: 11, name: "Alfonso Blanco", pos: "DEL", nat: "México" },
      ],
    },
    {
      id: "pachuca",
      espnId: 234,
      name: "Club de Fútbol Pachuca",
      short: "Pachuca",
      founded: 1901,
      city: "Pachuca, Hidalgo",
      stadium: "Estadio Hidalgo",
      capacity: 30000,
      nicknames: ["Tuzos"],
      titles: 7,
      runnersUp: 4,
      lastTitle: "Apertura 2022",
      colors: "Azul y blanco",
      history:
        "Los Tuzos son pioneros del fútbol en México (1901) y un modelo de cantera y exportación de talentos. El Huracán es célebre por su ambiente.",
      legends: [
        { name: "Gabriel Caballero", note: "Ídolo y DT" },
        { name: "Christian Giménez", note: "El Chaco" },
        { name: "Miguel Calero", note: "Portero colombiano" },
        { name: "Juan Carlos Cacho", note: "Delantero histórico" },
        { name: "Jaime Correa", note: "Volante de marca" },
      ],
      squad: [
        { n: 13, name: "Carlos Moreno", pos: "POR", nat: "México" },
        { n: 22, name: "Gustavo Cabral", pos: "DEF", nat: "Argentina" },
        { n: 32, name: "Miguel Rodríguez", pos: "DEF", nat: "México" },
        { n: 8, name: "Bryan González", pos: "DEF", nat: "México" },
        { n: 5, name: "Pedro Pedraza", pos: "MED", nat: "México" },
        { n: 6, name: "Érik Montiel", pos: "MED", nat: "México" },
        { n: 10, name: "Érick Sánchez", pos: "MED", nat: "México" },
        { n: 23, name: "Salomón Rondón", pos: "DEL", nat: "Venezuela" },
        { n: 9, name: "Felipe Medina", pos: "DEL", nat: "México" },
        { n: 11, name: "Owen González", pos: "DEL", nat: "México" },
        { n: 7, name: "Oussama Idrissi", pos: "DEL", nat: "Marruecos" },
      ],
    },
    {
      id: "santos",
      espnId: 225,
      name: "Club Santos Laguna",
      short: "Santos Laguna",
      founded: 1983,
      city: "Torreón, Coahuila",
      stadium: "Estadio Corona (TSM)",
      capacity: 30001,
      nicknames: ["Guerreros"],
      titles: 6,
      runnersUp: 5,
      lastTitle: "Clausura 2018",
      colors: "Verde y blanco",
      history:
        "Santos Laguna nació en la Comarca Lagunera y se consolidó como un club protagonista desde los 90, con una afición muy intensa en el TSM.",
      legends: [
        { name: "Jared Borgetti", note: "Máximo goleador" },
        { name: "Sigifredo Mercado", note: "Volante histórico" },
        { name: "Oswaldo Sánchez", note: "Portero ídolo" },
        { name: "Rodrigo Ruiz", note: "El Pony" },
        { name: "Juan Pablo Rodríguez", note: "El Chato" },
      ],
      squad: [
        { n: 1, name: "Carlos Acevedo", pos: "POR", nat: "México" },
        { n: 20, name: "Hugo Rodríguez", pos: "DEF", nat: "México" },
        { n: 23, name: "Raúl López", pos: "DEF", nat: "México" },
        { n: 2, name: "Bruno Amione", pos: "DEF", nat: "Argentina" },
        { n: 8, name: "Pedro Aquino", pos: "MED", nat: "Perú" },
        { n: 16, name: "Aldo López", pos: "MED", nat: "México" },
        { n: 10, name: "Fran Villalba", pos: "MED", nat: "España" },
        { n: 19, name: "Santiago Muñóz", pos: "DEL", nat: "México" },
        { n: 9, name: "Harold Preciado", pos: "DEL", nat: "Colombia" },
        { n: 7, name: "Emmanuel Echeverría", pos: "DEL", nat: "México" },
        { n: 11, name: "Choco Lozano", pos: "DEL", nat: "Honduras" },
      ],
    },
    {
      id: "pumas",
      espnId: 233,
      name: "Club Universidad Nacional",
      short: "Pumas UNAM",
      founded: 1954,
      city: "Ciudad de México",
      stadium: "Estadio Olímpico Universitario",
      capacity: 72000,
      nicknames: ["Pumas", "Universitarios"],
      titles: 7,
      runnersUp: 8,
      lastTitle: "Clausura 2011",
      colors: "Azul y dorado",
      history:
        "Los Pumas representan a la UNAM y han sido semillero de grandes talentos. El Olímpico Universitario es uno de los escenarios más emblemáticos del país.",
      legends: [
        { name: "Hugo Sánchez", note: "Máximo ídolo" },
        { name: "Cabinho", note: "Goleador brasileño" },
        { name: "Ricardo Ferretti", note: "Tuca · jugador y DT" },
        { name: "Jorge Campos", note: "Portero icónico" },
        { name: "Luis García", note: "Delantero canterano" },
      ],
      squad: [
        { n: 1, name: "Julio González", pos: "POR", nat: "México" },
        { n: 3, name: "Nathan Silva", pos: "DEF", nat: "Brasil" },
        { n: 6, name: "Pablo Bennevendo", pos: "DEF", nat: "México" },
        { n: 13, name: "Pablo Bennevendo", pos: "DEF", nat: "México" },
        { n: 8, name: "José Caicedo", pos: "MED", nat: "Colombia" },
        { n: 17, name: "Jorge Ruvalcaba", pos: "MED", nat: "México" },
        { n: 10, name: "Eduardo Salvio", pos: "MED", nat: "Argentina" },
        { n: 7, name: "Rodrigo López", pos: "MED", nat: "México" },
        { n: 9, name: "Guillermo Martínez", pos: "DEL", nat: "México" },
        { n: 11, name: "César Huerta", pos: "DEL", nat: "México" },
        { n: 19, name: "Robert Ergas", pos: "DEL", nat: "Uruguay" },
      ],
    },
    {
      id: "atlas",
      espnId: 216,
      name: "Atlas Fútbol Club",
      short: "Atlas",
      founded: 1916,
      city: "Guadalajara, Jalisco",
      stadium: "Estadio Jalisco",
      capacity: 55110,
      nicknames: ["Rojinegros", "La Academia"],
      titles: 3,
      runnersUp: 3,
      lastTitle: "Apertura 2021",
      colors: "Rojo y negro",
      history:
        "La Academia es famosa por su cantera. Tras décadas de espera, el bicampeonato 2021-22 devolvió a Atlas a la cima del fútbol mexicano.",
      legends: [
        { name: "Rafael Márquez", note: "Canterano mundial" },
        { name: "Andrés Guardado", note: "Canterano europeo" },
        { name: "Juan Carlos Chávez", note: "Ídolo local" },
        { name: "Jared Borgetti", note: "Paso goleador" },
        { name: "Pedro Pineda", note: "Delantero histórico" },
      ],
      squad: [
        { n: 12, name: "Camilo Vargas", pos: "POR", nat: "Colombia" },
        { n: 5, name: "Anderson Santamaría", pos: "DEF", nat: "Perú" },
        { n: 13, name: "Gaddi Aguirre", pos: "DEF", nat: "México" },
        { n: 14, name: "Luis Reyes", pos: "DEF", nat: "México" },
        { n: 26, name: "Aldo Rocha", pos: "MED", nat: "México" },
        { n: 18, name: "Jeremy Márquez", pos: "MED", nat: "México" },
        { n: 10, name: "Éduard Bolaños", pos: "MED", nat: "Colombia" },
        { n: 8, name: "Mateus Dórial", pos: "DEL", nat: "Brasil" },
        { n: 9, name: "José Lozano", pos: "DEL", nat: "México" },
        { n: 7, name: "Raymundo Fulgencio", pos: "DEL", nat: "México" },
        { n: 11, name: "Juan Zapata", pos: "DEL", nat: "Colombia" },
      ],
    },
    {
      id: "necaxa",
      espnId: 229,
      name: "Club Necaxa",
      short: "Necaxa",
      founded: 1923,
      city: "Aguascalientes, Ags.",
      stadium: "Estadio Victoria",
      capacity: 25500,
      nicknames: ["Rayos", "Los Electricistas"],
      titles: 3,
      runnersUp: 3,
      lastTitle: "Invierno 1998",
      colors: "Rojo y blanco",
      history:
        "Los Rayos tuvieron su era dorada en los 90. Hoy representan a Aguascalientes con una identidad combativa y afición leal en el Victoria.",
      legends: [
        { name: "Álex Aguinaga", note: "Ídolo ecuatoriano" },
        { name: "Ricardo Peláez", note: "Goleador" },
        { name: "Alberto García Aspe", note: "Volante mundialista" },
        { name: "Ivo Basay", note: "Delantero chileno" },
        { name: "José María Higareda", note: "Defensa histórico" },
      ],
      squad: [
        { n: 1, name: "Rafael Ramírez", pos: "POR", nat: "México" },
        { n: 4, name: "Alexis Peña", pos: "DEF", nat: "México" },
        { n: 3, name: "Agustín Oliveros", pos: "DEF", nat: "Uruguay" },
        { n: 2, name: "Emilio Lara", pos: "DEF", nat: "México" },
        { n: 16, name: "Fernando Arce", pos: "MED", nat: "México" },
        { n: 8, name: "Diego Gómez", pos: "MED", nat: "Paraguay" },
        { n: 10, name: "Ricardo Monreal", pos: "MED", nat: "México" },
        { n: 7, name: "Alejandro Andrade", pos: "DEL", nat: "México" },
        { n: 9, name: "Tomás Badaloni", pos: "DEL", nat: "Argentina" },
        { n: 11, name: "Brayan Garnica", pos: "DEL", nat: "México" },
        { n: 19, name: "José Paradela", pos: "MED", nat: "Argentina" },
      ],
    },
    {
      id: "puebla",
      espnId: 231,
      name: "Club Puebla",
      short: "Puebla",
      founded: 1944,
      city: "Puebla, Puebla",
      stadium: "Estadio Cuauhtémoc",
      capacity: 51726,
      nicknames: ["La Franja"],
      titles: 2,
      runnersUp: 2,
      lastTitle: "1992-93",
      colors: "Azul y blanco con franja",
      history:
        "La Franja es el orgullo de Puebla. Bicampeón en la historia del profesionalismo y dueño de una de las aficiones más fieles del centro del país.",
      legends: [
        { name: "Carlos Poblete", note: "Goleador chileno" },
        { name: "Jorge Campos", note: "Paso como portero" },
        { name: "Eusebio Salazar", note: "Ídolo local" },
        { name: "Ángel Comizzo", note: "Portero recordado" },
        { name: "Mario Hernández", note: "Volante histórico" },
      ],
      squad: [
        { n: 1, name: "Julio Baudoin", pos: "POR", nat: "México" },
        { n: 4, name: "Gustavo Ferrareis", pos: "DEF", nat: "Brasil" },
        { n: 3, name: "Sebastián Olmedo", pos: "DEF", nat: "Paraguay" },
        { n: 21, name: "Brayan Angulo", pos: "DEF", nat: "Colombia" },
        { n: 8, name: "Javier Salas", pos: "MED", nat: "México" },
        { n: 10, name: "Kevin Velasco", pos: "MED", nat: "Colombia" },
        { n: 6, name: "Pablo González", pos: "MED", nat: "México" },
        { n: 7, name: "Lucas Cavallini", pos: "DEL", nat: "Canadá" },
        { n: 9, name: "Santiago Ormeño", pos: "DEL", nat: "México" },
        { n: 11, name: "Emiliano Gómez", pos: "DEL", nat: "Uruguay" },
        { n: 19, name: "Raúl Castillo", pos: "MED", nat: "México" },
      ],
    },
    {
      id: "queretaro",
      espnId: 222,
      name: "Querétaro Fútbol Club",
      short: "Querétaro",
      founded: 1950,
      city: "Santiago de Querétaro, Qro.",
      stadium: "Estadio Corregidora",
      capacity: 33162,
      nicknames: ["Gallos Blancos"],
      titles: 0,
      runnersUp: 0,
      lastTitle: "—",
      colors: "Azul y negro",
      history:
        "Los Gallos Blancos representan a Querétaro con una afición creciente. El Corregidora ha sido sede de mundiales juveniles y partidos de alta tensión.",
      legends: [
        { name: "Miguel Sabah", note: "Goleador recordado" },
        { name: "Carlos Bueno", note: "Delantero uruguayo" },
        { name: "Danilinho", note: "Creativo brasileño" },
        { name: "Ronald Raldes", note: "Defensa boliviano" },
        { name: "Sinha", note: "Paso por el club" },
      ],
      squad: [
        { n: 1, name: "Guillermo Allison", pos: "POR", nat: "México" },
        { n: 4, name: "Óscar Manzanárez", pos: "DEF", nat: "México" },
        { n: 3, name: "Pablo Ortíz", pos: "DEF", nat: "México" },
        { n: 12, name: "Jaime Gómez", pos: "DEF", nat: "México" },
        { n: 5, name: "Kevin Escamilla", pos: "MED", nat: "México" },
        { n: 10, name: "Pablo Barrera", pos: "MED", nat: "México" },
        { n: 8, name: "Federico Lértora", pos: "MED", nat: "Argentina" },
        { n: 7, name: "Lucas Rodríguez", pos: "MED", nat: "Argentina" },
        { n: 9, name: "José Alberto Jiménez", pos: "DEL", nat: "México" },
        { n: 11, name: "Ayrton Cisneros", pos: "DEL", nat: "México" },
        { n: 19, name: "Ettson Ayón", pos: "DEL", nat: "México" },
      ],
    },
    {
      id: "tijuana",
      espnId: 10125,
      name: "Club Tijuana Xoloitzcuintles de Caliente",
      short: "Tijuana",
      founded: 2007,
      city: "Tijuana, Baja California",
      stadium: "Estadio Caliente",
      capacity: 27333,
      nicknames: ["Xolos"],
      titles: 1,
      runnersUp: 0,
      lastTitle: "Apertura 2012",
      colors: "Rojo y negro",
      history:
        "Los Xolos son un club joven que en pocos años conquistó el título de liga (2012) y se consolidó en la frontera norte con un proyecto ambicioso.",
      legends: [
        { name: "Dely Valdés", note: "DT del título" },
        { name: "Dayro Moreno", note: "Goleador colombiano" },
        { name: "Félix Galván", note: "Portero del campeonato" },
        { name: "Richard Ruiz", note: "Volante histórico" },
        { name: "Joe Corona", note: "Canterano-fronterizo" },
      ],
      squad: [
        { n: 1, name: "Antonio Rodríguez", pos: "POR", nat: "México" },
        { n: 3, name: "Nicolás Díaz", pos: "DEF", nat: "Chile" },
        { n: 4, name: "Unai Bilbao", pos: "DEF", nat: "España" },
        { n: 16, name: "Alejandro Gómez", pos: "DEF", nat: "México" },
        { n: 8, name: "Domingo Blanco", pos: "MED", nat: "Argentina" },
        { n: 10, name: "Kevin Castañeda", pos: "MED", nat: "México" },
        { n: 20, name: "Fernando Madrigal", pos: "MED", nat: "México" },
        { n: 7, name: "Efraín Álvarez", pos: "MED", nat: "México" },
        { n: 9, name: "Carlos González", pos: "DEL", nat: "Paraguay" },
        { n: 11, name: "Christian Rivera", pos: "MED", nat: "Colombia" },
        { n: 19, name: "José Franco", pos: "DEL", nat: "México" },
      ],
    },
    {
      id: "juarez",
      espnId: 17851,
      name: "Fútbol Club Juárez",
      short: "FC Juárez",
      founded: 2015,
      city: "Ciudad Juárez, Chihuahua",
      stadium: "Estadio Olímpico Benito Juárez",
      capacity: 19703,
      nicknames: ["Bravos"],
      titles: 0,
      runnersUp: 0,
      lastTitle: "—",
      colors: "Verde y negro",
      history:
        "Los Bravos representan a Ciudad Juárez en Liga MX. Un proyecto fronterizo joven que busca consolidarse con identidad local y ambición deportiva.",
      legends: [
        { name: "Darío Lezcano", note: "Goleador referente" },
        { name: "Gabriel Hauche", note: "Extremo argentino" },
        { name: "Brian Fernández", note: "Delantero recordado" },
        { name: "Matías García", note: "Volante" },
        { name: "Pol García", note: "Defensa" },
      ],
      squad: [
        { n: 1, name: "Sebastián Jurado", pos: "POR", nat: "México" },
        { n: 4, name: "José Abella", pos: "DEF", nat: "México" },
        { n: 3, name: "Moisés Mosquera", pos: "DEF", nat: "Colombia" },
        { n: 26, name: "Francisco Nevárez", pos: "DEF", nat: "México" },
        { n: 8, name: "Dario Lezcano", pos: "DEL", nat: "Paraguay" },
        { n: 10, name: "Diego Dibusz", pos: "MED", nat: "Argentina" },
        { n: 6, name: "Guilherme Castilho", pos: "MED", nat: "Brasil" },
        { n: 7, name: "Ángel Zaldívar", pos: "DEL", nat: "México" },
        { n: 9, name: "Óscar Estupiñán", pos: "DEL", nat: "Colombia" },
        { n: 11, name: "Jonathan González", pos: "MED", nat: "México" },
        { n: 19, name: "Avilés Hurtado", pos: "DEL", nat: "Colombia" },
      ],
    },
    {
      id: "san-luis",
      espnId: 15720,
      name: "Atlético de San Luis",
      short: "Atlético San Luis",
      founded: 2013,
      city: "San Luis Potosí, S.L.P.",
      stadium: "Estadio Alfonso Lastras",
      capacity: 27000,
      nicknames: ["Tuneros", "Roji-Blancos"],
      titles: 0,
      runnersUp: 1,
      lastTitle: "—",
      colors: "Rojo y blanco",
      history:
        "Vinculado históricamente al Atlético de Madrid, el club potosino pelea en Liga MX con identidad rojiblanca y una afición creciente en el Lastras.",
      legends: [
        { name: "Nicolás Ibáñez", note: "Goleador estelar" },
        { name: "Mateus Vital", note: "Creativo" },
        { name: "Jürgen Damm", note: "Velocidad por banda" },
        { name: "Unai Bilbao", note: "Defensa vasco" },
        { name: "Ramón Juárez", note: "Canterano-defensa" },
      ],
      squad: [
        { n: 1, name: "Andrés Sánchez", pos: "POR", nat: "México" },
        { n: 4, name: "Julio Domínguez", pos: "DEF", nat: "México" },
        { n: 5, name: "Ricardo Chávez", pos: "DEF", nat: "México" },
        { n: 18, name: "Aldo Cruz", pos: "DEF", nat: "México" },
        { n: 8, name: "Óscar Macías", pos: "MED", nat: "México" },
        { n: 10, name: "Javier Güémez", pos: "MED", nat: "México" },
        { n: 6, name: "Jordan Carrillo", pos: "MED", nat: "México" },
        { n: 7, name: "Yan Phillipe", pos: "DEL", nat: "Brasil" },
        { n: 9, name: "Léo Bonatini", pos: "DEL", nat: "Brasil" },
        { n: 11, name: "Vitinho", pos: "DEL", nat: "Brasil" },
        { n: 19, name: "Franck Boli", pos: "DEL", nat: "Costa de Marfil" },
      ],
    },

    {
      id: "atlante",
      espnId: 226,
      name: "Atlante Fútbol Club",
      short: "Atlante",
      founded: 1916,
      city: "Ciudad de México / Cancún",
      stadium: "Estadio Ciudad de los Deportes",
      capacity: 33000,
      nicknames: ["Los Potros de Hierro", "Azulgranas"],
      titles: 3,
      runnersUp: 4,
      lastTitle: "Apertura 2007",
      colors: "Azul y grana",
      history:
        "Atlante es uno de los clubes históricos del fútbol mexicano, tricampeón de liga. Tras etapas en Cancún y el ascenso, vuelve a competir en la máxima categoría con su identidad azulgrana.",
      legends: [
        { name: "Cabinho", note: "Goleador brasileño histórico" },
        { name: "Hugo Sánchez", note: "Paso en su carrera" },
        { name: "Luis Roberto Alves Zague", note: "Delantero ídolo" },
        { name: "Félix Fernández", note: "Portero referente" },
        { name: "René Isidoro García", note: "Volante histórico" },
      ],
      squad: [],
    },
  ];

  function list() {
    return clubs.slice().sort(function (a, b) {
      return a.name.localeCompare(b.name, "es");
    });
  }

  function byId(id) {
    id = String(id || "").toLowerCase();
    return (
      clubs.find(function (c) {
        return c.id === id;
      }) || null
    );
  }

  function byEspn(espnId) {
    espnId = Number(espnId);
    return (
      clubs.find(function (c) {
        return Number(c.espnId) === espnId;
      }) || null
    );
  }

  return { list: list, byId: byId, byEspn: byEspn, all: clubs };
})();
